baseURL: "https://kiwamizamurai.github.io/"
title: terakoya
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  math: true # for latex
  comments: true # for giscus

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: terakoya
  description: "OR than ML"
  # keywords: [Blog, Portfolio, PaperMod]
  author: kiwamizamurai
  # author: ["Me", "You"] # multiple authors
  images: ["https://avatars.githubusercontent.com/u/24860100"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://avatars.githubusercontent.com/u/24860100"
    favicon16x16: "https://avatars.githubusercontent.com/u/24860100"
    favicon32x32: "https://avatars.githubusercontent.com/u/24860100"
    apple_touch_icon: "https://avatars.githubusercontent.com/u/24860100"
    safari_pinned_tab: "https://avatars.githubusercontent.com/u/24860100"

  label:
    text: "Home"
    icon: "https://avatars.githubusercontent.com/u/24860100"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "寺子屋"
    subtitle: "OR than ML 👐 🍑🍑"
    imageUrl: "https://avatars.githubusercontent.com/u/24860100"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Search
        url: search

  # home-info mode
  homeInfoParams:
    Title: "寺子屋"
    Content: "OR than ML 👐 🍑🍑"

  socialIcons:
    - name: github
      url: "https://github.com/kiwamizamurai"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kiwamizamurai/kiwamizamurai.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: "search"
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

# for search page
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary